services:
  bank_router:
    ports:
      - "0.0.0.0:${DBO_HOST_HTTP_PORT}:${PROXY_HTTP_PORT}/tcp"
      - "0.0.0.0:${DBO_HOST_HTTPS_PORT}:${PROXY_HTTPS_PORT}/tcp"
      - "0.0.0.0:${ARM_OPER_HOST_SSH_PORT}:${ARM_OPER_HOST_SSH_PORT}/tcp"
      - "0.0.0.0:${ARM_CASH_HOST_SSH_PORT}:${ARM_CASH_HOST_SSH_PORT}/tcp"
      - "0.0.0.0:${ARM_ACC_HOST_SSH_PORT}:${ARM_ACC_HOST_SSH_PORT}/tcp"
      - "0.0.0.0:${ARM_IT_HOST_SSH_PORT}:${ARM_IT_HOST_SSH_PORT}/tcp"
      - "0.0.0.0:${ARM_OPER_HOST_RDP_PORT}:${ARM_OPER_HOST_RDP_PORT}/tcp"
      - "0.0.0.0:${ARM_CASH_HOST_RDP_PORT}:${ARM_CASH_HOST_RDP_PORT}/tcp"
      - "0.0.0.0:${ARM_ACC_HOST_RDP_PORT}:${ARM_ACC_HOST_RDP_PORT}/tcp"
      - "0.0.0.0:${ARM_IT_HOST_RDP_PORT}:${ARM_IT_HOST_RDP_PORT}/tcp"
  bank_vpn:
    ports:
      - "0.0.0.0:${VPN_HOST_PORT}:${VPN_PORT}/udp"
